# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='golfscore',
            old_name='holeno',
            new_name='holeno1',
        ),
        migrations.RenameField(
            model_name='golfscore',
            old_name='par',
            new_name='par1',
        ),
        migrations.RenameField(
            model_name='golfscore',
            old_name='score',
            new_name='score1',
        ),
        migrations.RemoveField(
            model_name='golfscore',
            name='chip',
        ),
        migrations.RemoveField(
            model_name='golfscore',
            name='drive',
        ),
        migrations.RemoveField(
            model_name='golfscore',
            name='putt',
        ),
        migrations.AddField(
            model_name='golfscore',
            name='approach1',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='golfscore',
            name='chip1',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='golfscore',
            name='drive1',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='golfscore',
            name='longiron1',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='golfscore',
            name='putt1',
            field=models.NullBooleanField(),
        ),
    ]
