# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0002_auto_20170114_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfscore',
            name='approach2',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='golfscore',
            name='chip2',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='golfscore',
            name='drive2',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='golfscore',
            name='holeno2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golfscore',
            name='longiron2',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='golfscore',
            name='par2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golfscore',
            name='putt2',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='golfscore',
            name='score2',
            field=models.IntegerField(default=0),
        ),
    ]
