# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0005_auto_20170114_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golfscore',
            name='back',
        ),
        migrations.RemoveField(
            model_name='golfscore',
            name='out',
        ),
        migrations.RemoveField(
            model_name='golfscore',
            name='total',
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach1',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach10',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach11',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach12',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach13',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach14',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach15',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach16',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach17',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach18',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach2',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach3',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach4',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach5',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach6',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach7',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach8',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach9',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip1',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip10',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip11',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip12',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip13',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip14',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip15',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip16',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip17',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip18',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip2',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip3',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip4',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip5',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip6',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip7',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip8',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip9',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive1',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive10',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive11',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive12',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive13',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive14',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive15',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive16',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive17',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive18',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive2',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive3',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive4',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive5',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive6',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive7',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive8',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive9',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='holeno1',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='holeno10',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='holeno11',
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='holeno12',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='holeno13',
            field=models.IntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='holeno14',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='holeno15',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='holeno16',
            field=models.IntegerField(default=16),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='holeno17',
            field=models.IntegerField(default=17),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='holeno18',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='holeno2',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='holeno3',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='holeno4',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='holeno5',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='holeno6',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='holeno7',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='holeno8',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='holeno9',
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron1',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron10',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron11',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron12',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron13',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron14',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron15',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron16',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron17',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron18',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron2',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron3',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron4',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron5',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron6',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron7',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron8',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron9',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='par1',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='par10',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='par11',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='par12',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='par13',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='par14',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='par15',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='par16',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='par17',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='par18',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='par2',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='par3',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='par4',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='par5',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='par6',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='par7',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='par8',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='par9',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt1',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt10',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt11',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt12',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt13',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt14',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt15',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt16',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt17',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt18',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt2',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt3',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt4',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt5',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt6',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt7',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt8',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt9',
            field=models.NullBooleanField(choices=[(True, 'Good'), (False, 'Bad'), (None, 'N/a')]),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score1',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score10',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score11',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score12',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score13',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score14',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score15',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score16',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score17',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score18',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score2',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score3',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score4',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score5',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score6',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score7',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score8',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score9',
            field=models.IntegerField(default=None),
        ),
    ]
