# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 11:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('golfapp', '0006_auto_20170121_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfscore',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='golfscores', to=settings.AUTH_USER_MODEL),
        ),
    ]
