# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 13:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0007_golfscore_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfscore',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
