# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0009_auto_20170219_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shotpercentages',
            name='approachp',
        ),
        migrations.RemoveField(
            model_name='shotpercentages',
            name='chipp',
        ),
        migrations.RemoveField(
            model_name='shotpercentages',
            name='drivep',
        ),
        migrations.RemoveField(
            model_name='shotpercentages',
            name='longironp',
        ),
        migrations.RemoveField(
            model_name='shotpercentages',
            name='puttp',
        ),
    ]
