# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0010_auto_20170219_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='shotpercentages',
            name='percents',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='shotpercentages',
            name='shottype',
            field=models.CharField(default='drive', max_length=200),
        ),
    ]
