# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0012_auto_20170221_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='shotpercentages',
            name='approachpercentage',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shotpercentages',
            name='chippercentage',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shotpercentages',
            name='drivepercentage',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shotpercentages',
            name='longironpercentage',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shotpercentages',
            name='puttpercentage',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score1',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score10',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score11',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score12',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score13',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score14',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score15',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score16',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score17',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score18',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score2',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score3',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score4',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score5',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score6',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score7',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score8',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='score9',
            field=models.IntegerField(default=4),
        ),
    ]
