# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0013_auto_20170221_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='XTitles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(max_length=50)),
            ],
        ),
    ]
