# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 20:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('golfapp', '0015_delete_xtitles'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseoutwards', models.IntegerField(default=1)),
                ('courseinwards', models.IntegerField(default=1)),
                ('coursepar', models.IntegerField(default=1)),
                ('scoreoutwards', models.IntegerField(default=1)),
                ('scoreinwards', models.IntegerField(default=1)),
                ('scoretotal', models.IntegerField(default=1)),
                ('overunderpar', models.IntegerField(default=1)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
