# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0016_totalscores'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfscore',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
