# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0017_golfscore_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GolfCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200)),
                ('par1', models.IntegerField(default=4)),
                ('par2', models.IntegerField(default=4)),
                ('par3', models.IntegerField(default=4)),
                ('par4', models.IntegerField(default=4)),
                ('par5', models.IntegerField(default=4)),
                ('par6', models.IntegerField(default=4)),
                ('par7', models.IntegerField(default=4)),
                ('par8', models.IntegerField(default=4)),
                ('par9', models.IntegerField(default=4)),
                ('par10', models.IntegerField(default=4)),
                ('par11', models.IntegerField(default=4)),
                ('par12', models.IntegerField(default=4)),
                ('par13', models.IntegerField(default=4)),
                ('par14', models.IntegerField(default=4)),
                ('par15', models.IntegerField(default=4)),
                ('par16', models.IntegerField(default=4)),
                ('par17', models.IntegerField(default=4)),
                ('par18', models.IntegerField(default=4)),
            ],
        ),
    ]
