# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0019_auto_20170331_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golfscore',
            name='holeno1',
        ),
    ]
