# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0020_remove_golfscore_holeno1'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfscore',
            name='holeno1',
            field=models.IntegerField(default=1),
        ),
    ]
