# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0022_auto_20170331_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfscore',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='golfapp.GolfCourses'),
        ),
    ]
