# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0023_auto_20170401_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='shotpercentages',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='golfapp.Golfscore'),
        ),
    ]
