# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0024_shotpercentages_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shotpercentages',
            name='course',
        ),
    ]
