# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0025_remove_shotpercentages_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='shotpercentages',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='golfapp.GolfCourses'),
        ),
        migrations.AddField(
            model_name='totalscores',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='golfapp.GolfCourses'),
        ),
    ]
