# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0026_auto_20170407_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='shotpercentages',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='totalscores',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
