# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0027_auto_20170407_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfscore',
            name='approach1',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach10',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach11',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach12',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach13',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach14',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach15',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach16',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach17',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach18',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach2',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach3',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach4',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach5',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach6',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach7',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach8',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='approach9',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip1',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip10',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip11',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip12',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip13',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip14',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip15',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip16',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip17',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip18',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip2',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip3',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip4',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip5',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip6',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip7',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip8',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='chip9',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive1',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive10',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive11',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive12',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive13',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive14',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive15',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive16',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive17',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive18',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive2',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive3',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive4',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive5',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive6',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive7',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive8',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='drive9',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron1',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron10',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron11',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron12',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron13',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron14',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron15',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron16',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron17',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron18',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron2',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron3',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron4',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron5',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron6',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron7',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron8',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='longiron9',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt1',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt10',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt11',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt12',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt13',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt14',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt15',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt16',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt17',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt18',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt2',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt3',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt4',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt5',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt6',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt7',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt8',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='putt9',
            field=models.NullBooleanField(choices=[(True, ''), (False, ''), (None, '')], default=None),
        ),
    ]
