# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 15:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('golfapp', '0028_auto_20170414_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaguetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('won', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('drawn', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('player', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
