# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0030_auto_20170415_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfscore',
            name='o1totalscore',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='golfscore',
            name='o2totalscore',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='golfscore',
            name='o3totalscore',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
