# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0032_auto_20170415_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfscore',
            name='o1totalscore',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='o2totalscore',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='golfscore',
            name='o3totalscore',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
