# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfapp', '0035_auto_20170415_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguetable',
            name='played',
            field=models.IntegerField(default=0),
        ),
    ]
