from django import forms
from django.forms import ModelForm, NumberInput
from .models import Golfscore

class PostForm(forms.ModelForm):

    class Meta:
        model = Golfscore
        fields = ('course', 'holeno1', 'par1', 'score1','drive1', 'longiron1', 'approach1', 'chip1', 'putt1',
         'holeno2', 'par2', 'score2','drive2', 'longiron2', 'approach2', 'chip2', 'putt2',
         'holeno3', 'par3', 'score3','drive3', 'longiron3', 'approach3', 'chip3', 'putt3',
         'holeno4', 'par4', 'score4','drive4', 'longiron4', 'approach4', 'chip4', 'putt4',
         'holeno5', 'par5', 'score5','drive5', 'longiron5', 'approach5', 'chip5', 'putt5',
         'holeno6', 'par6', 'score6','drive6', 'longiron6', 'approach6', 'chip6', 'putt6',
         'holeno7', 'par7', 'score7','drive7', 'longiron7', 'approach7', 'chip7', 'putt7',
         'holeno8', 'par8', 'score8','drive8', 'longiron8', 'approach8', 'chip8', 'putt8',
         'holeno9', 'par9', 'score9','drive9', 'longiron9', 'approach9', 'chip9', 'putt9',
         'holeno10', 'par10', 'score10','drive10', 'longiron10', 'approach10', 'chip10', 'putt10',
         'holeno11', 'par11', 'score11','drive11', 'longiron11', 'approach11', 'chip11', 'putt11',
         'holeno12', 'par12', 'score12','drive12', 'longiron12', 'approach12', 'chip12', 'putt12',
         'holeno13', 'par13', 'score13','drive13', 'longiron13', 'approach13', 'chip13', 'putt13',
         'holeno14', 'par14', 'score14','drive14', 'longiron14', 'approach14', 'chip14', 'putt14',
         'holeno15', 'par15', 'score15','drive15', 'longiron15', 'approach15', 'chip15', 'putt15',
         'holeno16', 'par16', 'score16','drive16', 'longiron16', 'approach16', 'chip16', 'putt16',
         'holeno17', 'par17', 'score17','drive17', 'longiron17', 'approach17', 'chip17', 'putt17',
         'holeno18', 'par18', 'score18','drive18', 'longiron18', 'approach18', 'chip18', 'putt18',
         'author',
         )
        widgets = {
            'holeno1': NumberInput(attrs={'class': 'classybox'}),
            'holeno2': NumberInput(attrs={'class': 'classybox'}),
            'holeno3': NumberInput(attrs={'class': 'classybox'}),
            'holeno4': NumberInput(attrs={'class': 'classybox'}),
            'holeno5': NumberInput(attrs={'class': 'classybox'}),
            'holeno6': NumberInput(attrs={'class': 'classybox'}),
            'holeno7': NumberInput(attrs={'class': 'classybox'}),
            'holeno8': NumberInput(attrs={'class': 'classybox'}),
            'holeno9': NumberInput(attrs={'class': 'classybox'}),
            'par1': NumberInput(attrs={'class': 'classybox'}),
            'par2': NumberInput(attrs={'class': 'classybox'}),
            'par3': NumberInput(attrs={'class': 'classybox'}),
            'par4': NumberInput(attrs={'class': 'classybox'}),
            'par5': NumberInput(attrs={'class': 'classybox'}),
            'par6': NumberInput(attrs={'class': 'classybox'}),
            'par7': NumberInput(attrs={'class': 'classybox'}),
            'par8': NumberInput(attrs={'class': 'classybox'}),
            'par9': NumberInput(attrs={'class': 'classybox'}),
            'score1': NumberInput(attrs={'class': 'classybox'}),
            'score2': NumberInput(attrs={'class': 'classybox'}),
            'score3': NumberInput(attrs={'class': 'classybox'}),
            'score4': NumberInput(attrs={'class': 'classybox'}),
            'score5': NumberInput(attrs={'class': 'classybox'}),
            'score6': NumberInput(attrs={'class': 'classybox'}),
            'score7': NumberInput(attrs={'class': 'classybox'}),
            'score8': NumberInput(attrs={'class': 'classybox'}),
            'score9': NumberInput(attrs={'class': 'classybox'}),
            'holeno10': NumberInput(attrs={'class': 'classybox'}),
            'holeno11': NumberInput(attrs={'class': 'classybox'}),
            'holeno12': NumberInput(attrs={'class': 'classybox'}),
            'holeno13': NumberInput(attrs={'class': 'classybox'}),
            'holeno14': NumberInput(attrs={'class': 'classybox'}),
            'holeno15': NumberInput(attrs={'class': 'classybox'}),
            'holeno16': NumberInput(attrs={'class': 'classybox'}),
            'holeno17': NumberInput(attrs={'class': 'classybox'}),
            'holeno18': NumberInput(attrs={'class': 'classybox'}),
            'par10': NumberInput(attrs={'class': 'classybox'}),
            'par11': NumberInput(attrs={'class': 'classybox'}),
            'par12': NumberInput(attrs={'class': 'classybox'}),
            'par13': NumberInput(attrs={'class': 'classybox'}),
            'par14': NumberInput(attrs={'class': 'classybox'}),
            'par15': NumberInput(attrs={'class': 'classybox'}),
            'par16': NumberInput(attrs={'class': 'classybox'}),
            'par17': NumberInput(attrs={'class': 'classybox'}),
            'par18': NumberInput(attrs={'class': 'classybox'}),
            'score10': NumberInput(attrs={'class': 'classybox'}),
            'score11': NumberInput(attrs={'class': 'classybox'}),
            'score12': NumberInput(attrs={'class': 'classybox'}),
            'score13': NumberInput(attrs={'class': 'classybox'}),
            'score14': NumberInput(attrs={'class': 'classybox'}),
            'score15': NumberInput(attrs={'class': 'classybox'}),
            'score16': NumberInput(attrs={'class': 'classybox'}),
            'score17': NumberInput(attrs={'class': 'classybox'}),
            'score18': NumberInput(attrs={'class': 'classybox'}),
        }
