from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class GolfCourses(models.Model):
    course = models.CharField(max_length=200)
    par1 = models.IntegerField(default=4)
    par2 = models.IntegerField(default=4)
    par3 = models.IntegerField(default=4)
    par4 = models.IntegerField(default=4)
    par5 = models.IntegerField(default=4)
    par6 = models.IntegerField(default=4)
    par7 = models.IntegerField(default=4)
    par8 = models.IntegerField(default=4)
    par9 = models.IntegerField(default=4)
    par10 = models.IntegerField(default=4)
    par11 = models.IntegerField(default=4)
    par12 = models.IntegerField(default=4)
    par13 = models.IntegerField(default=4)
    par14 = models.IntegerField(default=4)
    par15 = models.IntegerField(default=4)
    par16 = models.IntegerField(default=4)
    par17 = models.IntegerField(default=4)
    par18 = models.IntegerField(default=4)

    def __str__(self):
        return self.course

CHOICES = (
    (True, ""),
    (False, ""),
    (None, "")

)

class Golfscore(models.Model):
    course = models.ForeignKey(GolfCourses, on_delete=models.CASCADE, null=True)
    score1 = models.IntegerField(default=4)
    drive1 = models.NullBooleanField(choices=CHOICES, default=None)
    longiron1 = models.NullBooleanField(choices=CHOICES, default=None)
    approach1 = models.NullBooleanField(choices=CHOICES, default=None)
    chip1 = models.NullBooleanField(choices=CHOICES, default=None)
    putt1 = models.NullBooleanField(choices=CHOICES, default=None)
    score2 = models.IntegerField(default=4)
    drive2 = models.NullBooleanField(choices=CHOICES, default=None)
    longiron2 = models.NullBooleanField(choices=CHOICES, default=None)
    approach2 = models.NullBooleanField(choices=CHOICES, default=None)
    chip2 = models.NullBooleanField(choices=CHOICES, default=None)
    putt2 = models.NullBooleanField(choices=CHOICES, default=None)
    score3 = models.IntegerField(default=4)
    drive3 = models.NullBooleanField(choices=CHOICES, default=None)
    longiron3 = models.NullBooleanField(choices=CHOICES, default=None)
    approach3 = models.NullBooleanField(choices=CHOICES, default=None)
    chip3 = models.NullBooleanField(choices=CHOICES, default=None)
    putt3 = models.NullBooleanField(choices=CHOICES, default=None)
    score4 = models.IntegerField(default=4)
    drive4 = models.NullBooleanField(choices=CHOICES, default=None)
    longiron4 = models.NullBooleanField(choices=CHOICES, default=None)
    approach4 = models.NullBooleanField(choices=CHOICES, default=None)
    chip4 = models.NullBooleanField(choices=CHOICES, default=None)
    putt4 = models.NullBooleanField(choices=CHOICES, default=None)
    score5 = models.IntegerField(default=4)
    drive5 = models.NullBooleanField(choices=CHOICES, default=None)
    longiron5 = models.NullBooleanField(choices=CHOICES, default=None)
    approach5 = models.NullBooleanField(choices=CHOICES, default=None)
    chip5 = models.NullBooleanField(choices=CHOICES, default=None)
    putt5 = models.NullBooleanField(choices=CHOICES, default=None)
    score6 = models.IntegerField(default=4)
    drive6 = models.NullBooleanField(choices=CHOICES, default=None)
    longiron6 = models.NullBooleanField(choices=CHOICES, default=None)
    approach6 = models.NullBooleanField(choices=CHOICES, default=None)
    chip6 = models.NullBooleanField(choices=CHOICES, default=None)
    putt6 = models.NullBooleanField(choices=CHOICES, default=None)
    score7 = models.IntegerField(default=4)
    drive7 = models.NullBooleanField(choices=CHOICES, default=None)
    longiron7 = models.NullBooleanField(choices=CHOICES, default=None)
    approach7 = models.NullBooleanField(choices=CHOICES, default=None)
    chip7 = models.NullBooleanField(choices=CHOICES, default=None)
    putt7 = models.NullBooleanField(choices=CHOICES, default=None)
    score8 = models.IntegerField(default=4)
    drive8 = models.NullBooleanField(choices=CHOICES, default=None)
    longiron8 = models.NullBooleanField(choices=CHOICES, default=None)
    approach8 = models.NullBooleanField(choices=CHOICES, default=None)
    chip8 = models.NullBooleanField(choices=CHOICES, default=None)
    putt8 = models.NullBooleanField(choices=CHOICES, default=None)
    score9 = models.IntegerField(default=4)
    drive9 = models.NullBooleanField(choices=CHOICES, default=None)
    longiron9 = models.NullBooleanField(choices=CHOICES, default=None)
    approach9 = models.NullBooleanField(choices=CHOICES, default=None)
    chip9 = models.NullBooleanField(choices=CHOICES, default=None)
    putt9 = models.NullBooleanField(choices=CHOICES, default=None)
    score10 = models.IntegerField(default=4)
    drive10 = models.NullBooleanField(choices=CHOICES, default=None)
    longiron10 = models.NullBooleanField(choices=CHOICES, default=None)
    approach10 = models.NullBooleanField(choices=CHOICES, default=None)
    chip10 = models.NullBooleanField(choices=CHOICES, default=None)
    putt10 = models.NullBooleanField(choices=CHOICES, default=None)
    score11 = models.IntegerField(default=4)
    drive11 = models.NullBooleanField(choices=CHOICES, default=None)
    longiron11 = models.NullBooleanField(choices=CHOICES, default=None)
    approach11 = models.NullBooleanField(choices=CHOICES, default=None)
    chip11 = models.NullBooleanField(choices=CHOICES, default=None)
    putt11 = models.NullBooleanField(choices=CHOICES, default=None)
    score12 = models.IntegerField(default=4)
    drive12 = models.NullBooleanField(choices=CHOICES, default=None)
    longiron12 = models.NullBooleanField(choices=CHOICES, default=None)
    approach12 = models.NullBooleanField(choices=CHOICES, default=None)
    chip12 = models.NullBooleanField(choices=CHOICES, default=None)
    putt12 = models.NullBooleanField(choices=CHOICES, default=None)
    score13 = models.IntegerField(default=4)
    drive13 = models.NullBooleanField(choices=CHOICES, default=None)
    longiron13 = models.NullBooleanField(choices=CHOICES, default=None)
    approach13 = models.NullBooleanField(choices=CHOICES, default=None)
    chip13 = models.NullBooleanField(choices=CHOICES, default=None)
    putt13 = models.NullBooleanField(choices=CHOICES, default=None)
    score14 = models.IntegerField(default=4)
    drive14 = models.NullBooleanField(choices=CHOICES, default=None)
    longiron14 = models.NullBooleanField(choices=CHOICES, default=None)
    approach14 = models.NullBooleanField(choices=CHOICES, default=None)
    chip14 = models.NullBooleanField(choices=CHOICES, default=None)
    putt14 = models.NullBooleanField(choices=CHOICES, default=None)
    score15 = models.IntegerField(default=4)
    drive15 = models.NullBooleanField(choices=CHOICES, default=None)
    longiron15 = models.NullBooleanField(choices=CHOICES, default=None)
    approach15 = models.NullBooleanField(choices=CHOICES, default=None)
    chip15 = models.NullBooleanField(choices=CHOICES, default=None)
    putt15 = models.NullBooleanField(choices=CHOICES, default=None)
    score16 = models.IntegerField(default=4)
    drive16 = models.NullBooleanField(choices=CHOICES, default=None)
    longiron16 = models.NullBooleanField(choices=CHOICES, default=None)
    approach16 = models.NullBooleanField(choices=CHOICES, default=None)
    chip16 = models.NullBooleanField(choices=CHOICES, default=None)
    putt16 = models.NullBooleanField(choices=CHOICES, default=None)
    score17 = models.IntegerField(default=4)
    drive17 = models.NullBooleanField(choices=CHOICES, default=None)
    longiron17 = models.NullBooleanField(choices=CHOICES, default=None)
    approach17 = models.NullBooleanField(choices=CHOICES, default=None)
    chip17 = models.NullBooleanField(choices=CHOICES, default=None)
    putt17 = models.NullBooleanField(choices=CHOICES, default=None)
    score18 = models.IntegerField(default=4)
    drive18 = models.NullBooleanField(choices=CHOICES, default=None)
    longiron18 = models.NullBooleanField(choices=CHOICES, default=None)
    approach18 = models.NullBooleanField(choices=CHOICES, default=None)
    chip18 = models.NullBooleanField(choices=CHOICES, default=None)
    putt18 = models.NullBooleanField(choices=CHOICES, default=None)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    published_date = models.DateTimeField(default=timezone.now)
    opponent1 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='opponent1', default=None, null=True, blank=True)
    opponent2 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='opponent2', default=None, null=True, blank=True)
    opponent3 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='opponent3', default=None, null=True, blank=True)
    o1totalscore = models.IntegerField(default=None, null=True, blank=True)
    o2totalscore = models.IntegerField(default=None, null=True, blank=True)
    o3totalscore = models.IntegerField(default=None, null=True, blank=True)

class ShotPercentages(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    drivepercentage = models.IntegerField(default=1)
    longironpercentage = models.IntegerField(default=1)
    approachpercentage = models.IntegerField(default=1)
    chippercentage = models.IntegerField(default=1)
    puttpercentage = models.IntegerField(default=1)
    course = models.ForeignKey(GolfCourses, on_delete=models.CASCADE, null=True)
    published_date = models.DateTimeField(default=timezone.now)

class TotalScores(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    courseoutwards = models.IntegerField(default=1)
    courseinwards = models.IntegerField(default=1)
    coursepar = models.IntegerField(default=1)
    scoreoutwards = models.IntegerField(default=1)
    scoreinwards = models.IntegerField(default=1)
    scoretotal = models.IntegerField(default=1)
    overunderpar = models.IntegerField(default=1)
    course = models.ForeignKey(GolfCourses, on_delete=models.CASCADE, null=True)
    published_date = models.DateTimeField(default=timezone.now)

class Leaguetable(models.Model):
    player = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    won = models.IntegerField(default=0)
    lost = models.IntegerField(default=0)
    drawn = models.IntegerField(default=0)
    points = models.IntegerField(default=0)
    played = models.IntegerField(default=0)

class Signup(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    published_date = models.DateTimeField(default=timezone.now)
    phonenumber = models.CharField(max_length=20)
